Add draw map and selection of points by the user
situmtech/situm-android-getting-started pull request #35
Opened 2019-04-04 11:18 UTC by lorenapereira

2019-04-04 11:26 UTC, CrisBarreiro requested changes

2019-04-04 11:26 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/drawroute/DrawRouteActivity.java
> +        if (intent != null)
Por convención, en el equipo de móvil siempre ponemos llaves en los if de una sola línea, para evitar problemas cuando necesitamos añadir una línea más y nos olvidamos de poner las llaves

2019-04-04 11:26 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/drawroute/DrawRouteActivity.java
> +        Coordinate c = new Coordinate(latLng.latitude, latLng.longitude);
Renombra estas variables para que tengan un nombre más descriptivo, porfa

2019-04-04 11:26 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/drawroute/DrawRouteActivity.java
> +                    Point pointDestination=createPoint(latLng);
Si te fijas, cuando hacemos igualaciones siempre ponemos espacios a ambos lados, es cuestión de gustos, pero debemos intentar que el estilo sea coherente con el resto de la aplicación

2019-04-04 11:26 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/drawroute/DrawRouteActivity.java
> +        getBuildingsCaseUse.cancel();
Es una tontería, pero esta variable debería ser useCase, no caseUse

2019-04-04 11:26 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/positioning/PositioningActivity.java
> +    private static final String BUILDING_ID = "5145";
Aquí debería seguir siendo YOUR_BUILDING_ID, supongo que se te quedó cambiado al probarlo en local

2019-04-04 11:30 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/drawroute/DrawRouteActivity.java
>                      DirectionsRequest directionsRequest = new DirectionsRequest.Builder()
Yo extraería toda esta parte de cálculo de ruta a un método, pienso que para un usuario que consulte los ejemplos resulta más fácil de entender

2019-04-04 12:02 UTC, adrinieto requested changes

2019-04-04 12:02 UTC, adrinieto commented on app/src/main/java/es/situm/gettingstarted/drawroute/DrawRouteActivity.java
> +        if (intent != null)
A mayores, estos dos ifs se pueden juntar en uno solo con un `&&`

2019-04-04 12:02 UTC, adrinieto commented on app/src/main/java/es/situm/gettingstarted/drawroute/SelectionBuildingListActivity.java
> +package es.situm.gettingstarted.drawroute;
Tengo la Pull Request #30 pendiente de mergear desde hace más de un mes :sweat_smile: que elimina parte de las activities duplicadas para seleccionar edificio y añade una forma más sencilla de obtener el edificio.
Creo que deberíamos mergear esa PR primero y así no añadimos esta Activity repetida.

2019-04-04 12:06 UTC, adrinieto commented on app/src/main/java/es/situm/gettingstarted/drawroute/SelectionBuildingListActivity.java
> +package es.situm.gettingstarted.drawroute;
Antes de mergearla tendría que validarse que todo sigue funcionando como antes, por eso sigue ahí...

2019-04-05 08:31 UTC, SilviaMRegueira approved these changes

2019-04-05 08:53 UTC, adrinieto requested changes

2019-04-05 08:53 UTC, adrinieto commented on app/src/main/java/es/situm/gettingstarted/guideinstructions/GetBuildingsCaseUse.java
> +    public interface Callback{
Cos cambios que fixemos estes 3 `public` xa non farían falta

2019-04-05 08:53 UTC, adrinieto commented on app/src/main/java/es/situm/gettingstarted/drawroute/DrawRouteActivity.java
> +    private GetBuildingsCaseUse getBuildingsUseCase = new GetBuildingsCaseUse();
Como agora chega o building como extra xa non é necesario.

2019-04-05 08:53 UTC, adrinieto commented on app/src/main/java/es/situm/gettingstarted/drawroute/DrawRouteActivity.java
> +                Toast.makeText(DrawRouteActivity.this, error.getMessage(), Toast.LENGTH_LONG).show();
Creo que deberíamos usar Snackbar o Toast pero no ambos.

2019-04-05 09:35 UTC, CrisBarreiro approved these changes

2019-04-05 11:42 UTC, adrinieto approved these changes

2019-04-05 12:10 UTC, merged