Upgrade navigator example
situmtech/situm-android-getting-started pull request #36
Opened 2019-04-11 08:44 UTC by lorenapereira

2019-04-11 11:32 UTC, CrisBarreiro requested changes

2019-04-11 11:32 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/guideinstructions/GuideInstructionsActivity.java
> +    private void checkLocationManager() {
Por qué es necesario hacer esto?

2019-04-11 11:32 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/guideinstructions/GuideInstructionsActivity.java
> +                if (!isDrawMap) {
El nombre es mejor que flag, pero yo le daría una vuelta igualmente

2019-04-11 11:32 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/guideinstructions/GuideInstructionsActivity.java
> +        this.googleMap.setOnMarkerClickListener(marker -> {
Yo extraería toda esta lógica del onMarkerClickListener

2019-04-11 11:32 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/guideinstructions/GuideInstructionsActivity.java
> +            p = getPoiFromMarker(marker);
Yo metería todo en una sola línea, y le llamaría poi en lugar de p, para que sea más claro, porque p también podría ser point

2019-04-11 11:32 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/guideinstructions/GuideInstructionsActivity.java
> +            if((current != null) && (destination != null)){
current debería tener un nombre más descriptivo, porque se hay que ir a mirar unas cuantas líneas más arriba para entender lo que se está haciendo aquí. De todos modos, te propongo afrontar esto de otra manera, que es como solemos trabajar nosotros:

```java
if (current == null= || destination == null) {
    return;
}
```

Y después toda la lógica que tengas que llevar a cabo en caso de que los datos de entrada sean válidos. Así cortas el flujo desde el primer momento, y te ahorras tener el código "bueno" con un nivel más de indentación

2019-04-11 11:32 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/guideinstructions/GuideInstructionsActivity.java
> +                getPoisCaseUse.get(building, new GetPoisCaseUse.Callback() {
Si se puede gestionar esto sin pintar los POIs, haciendo un longpress, mejor, porque simplificamos el ejemplo

2019-04-11 11:32 UTC, CrisBarreiro commented on app/src/main/java/es/situm/gettingstarted/guideinstructions/GuideInstructionsActivity.java
> +        for(Poi p : poiListFloor){
Yo lo renombraría a poisInCurrentFloor

2019-04-15 07:44 UTC, AdrianRegueira commented on app/src/main/java/es/situm/gettingstarted/guideinstructions/GuideInstructionsActivity.java
> +    private void onMapClickListener(GoogleMap googleMap, LatLng latLng) {
Este metodo podría tener un nombre mas descriptivo, realmente no es un listener

2019-04-15 07:48 UTC, SilviaMRegueira approved these changes

2019-04-15 08:40 UTC, merged